version: "3.5"

services:
  api:
    ports:
      - "5001:5000"
    build:
      context: .
      dockerfile: ./mock-api/Dockerfile
    environment:
      - APP_HOST=http://app
      - APP_PORT=3000
  app:
    ports:
      - "3001:3000"
    build:
      context: .
    depends_on:
      - api
    environment:
      - MOCK_API_HOST=api
      - MOCK_API_PORT=5000

  e2e:
    image: cypress/included:3.4.1
    working_dir: /app
    environment:
      - CYPRESS_baseUrl=http://app:3000
      - DEBUG=cypress:*
      - NO_PROXY=localhost,app,api
    depends_on:
      - app
      - api
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json

